apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - name: hello-container
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo "Hello K8s!!" && sleep 3600']
      restartPolicy: IfNotPresent


